version: "3.9"

services:
  db:
    image: postgres:15
    container_name: infection-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: infection_db
    ports:
      - "5432:5432"
    volumes:
      # Persistent DB-Cluster
      - pgdata:/var/lib/postgresql/data
      # Init scripts (run only when the DB is initialized)
      - ./db/init:/docker-entrypoint-initdb.d:ro

volumes:
  pgdata: